overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-odsr.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - "tests/requirements.txt": "tests/custom_req.txt.jj2"
  - "tests/base.py": "tests/base.py"
  - "pyexcel_odsr/_version.py": "version.py.jj2"
  - setup.py: custom_setup.py.jj2
