overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel_odsr.yml
targets:
  - README.rst: custom_readme.rst.jj2
  - setup.py: custom_setup.py.jj2
  - .travis.yml: custom_travis.yml.jj2
  - "tests/requirements.txt": "tests/custom_req.txt.jj2"
  - "tests/test_filter.py": "tests/test_filter.py.jj2"
  - "tests/test_formatters.py": "tests/test_formatters.py"
  - "tests/test_stringio.py": "tests/test_stringio.py.jj2"
  - "tests/base.py": "tests/base.py"
  - "pyexcel_odsr/_version.py": "version.py.jj2"
